default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: seed_sso_development
  username: postgres
  password: 12345678
  host: localhost
  port: 5432
test:
  <<: *default
  database: seed_sso_test
  username: postgres
  password: 12345678
  host: localhost
  port: 5432
production:
  primary: &primary_production
    <<: *default
    database: seed_sso_production
    username: seed_sso
    password: <%= ENV["seed_sso_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: seed_sso_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: seed_sso_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: seed_sso_production_cable
    migrations_paths: db/cable_migrate